test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>


openstack:
  service: OpenStack
  container: <%= ENV['OPENSTACK_CONTAINER'] %>
  credentials:
    openstack_auth_url: <%= ENV['OPENSTACK_AUTH_URL'] %>
    openstack_username: <%= ENV['OPENSTACK_USERNAME'] %>
    openstack_api_key: <%= ENV['OPENSTACK_API_KEY'] %>
    openstack_region: <%= ENV['OPENSTACK_REGION'] %>
    openstack_temp_url_key: <%= ENV['OPENSTACK_TEMP_URL_KEY'] %>
  connection_options: # optional
    chunk_size: 2097152 # 2MBs - 1MB is the default
